#!/usr/bin/env bash
if [ "$EUID" -ne 0 ]
  then echo "please run with root privilleges"
  exit
fi
sudo cp ./sqlconf /etc/mysql/my.cnf
echo "configured mysql"
sudo systemctl enable mysql
echo "enabled mysql"
sudo mysql -u root < initializeMySql.sql
echo "initialized bot database and granted privilleges"
