#!/usr/bin/env bash
if [ -f "./pid" ]; then
    pid=`cat ./pid`
    echo "bot was running with PID "$pid", stopped"
    kill -9 $pid
    rm ./pid
else
    if [ $# = 1 ]; then
        echo "bot was not running previously"
    else
        echo "bot is not running. start with ./start or use \`ps\` to find and kill its lost process"
    fi
fi
